suasor/authenticas/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

app_name = 'authenticas'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^novus/', views.signup, name='signup'),
]

suasor/praedicto/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views
from .auxilium import TRAIN_SET_SIZE

app_name = 'praedicto'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^train/(?P<retrain>(True|False))$', views.train, name='train'),
    url(r'^train/(?P<user_id_rated>[0-9a-zA-Z.]+)_(?P<grades>[01]{{1,{}}})$'.format(TRAIN_SET_SIZE), views.train, name='train_finished'),
]

suasor/strigili/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

app_name = 'strigili'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

suasor/suasor/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^strigili/', include('strigili.urls')),
    url(r'^praedicto/', include('praedicto.urls')),
    url(r'^authenticas/', include('authenticas.urls'))
]

suasor/authenticas/models.py
from django.db import models

class User(models.Model):
    user_id = models.TextField(primary_key=True)
    password = models.TextField()

suasor/suasor/models.py
from django.db import models


class Friendship(models.Model):
    user1 = models.TextField()
    user2 = models.TextField()


class LogType(models.Model):
    name = models.CharField(max_length=10)


class Log(models.Model):
    at_time = models.CharField(max_length=27)
    type = models.ForeignKey(LogType)
    in_package = models.TextField()
    in_function = models.TextField()
    description = models.TextField()


class Rating(models.Model):
    user1 = models.TextField()
    user2 = models.TextField()
    grade = models.NullBooleanField()
    trainset = models.NullBooleanField() # Denotes whether grade was inserted during training.


class UserData(models.Model):
    user_id = models.TextField(primary_key=True)
    name = models.TextField(blank=True, null=True)
    birthday = models.TextField(blank=True, null=True)
    lives_in = models.TextField(blank=True, null=True)
    comes_from = models.TextField(blank=True, null=True)
    study = models.TextField(blank=True, null=True)
    picture_url = models.TextField(blank=True, null=True)
    married = models.NullBooleanField()
    in_relationship = models.NullBooleanField()
    has_saved_picture = models.BooleanField(default=False)

suasor/authenticas/forms.py
from django import forms

class SuasorLoginForm(forms.Form):
    user_id = forms.CharField(label="", help_text="", max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Facebook user ID'}))
    password = forms.CharField(label="", help_text="", max_length=20, widget=forms.PasswordInput(attrs={'placeholder': 'Password for Suasor'}))

class SuasorSignupForm(forms.Form):
    user_id = forms.CharField(label="", help_text="", max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Facebook user ID'}))
    password1 = forms.CharField(label="", help_text="", max_length=20, widget=forms.PasswordInput(attrs={'placeholder': 'Password for Suasor'}))
    password2 = forms.CharField(label="", help_text="", max_length=20, widget=forms.PasswordInput(attrs={'placeholder': 'Repeat password'}))

suasor/strigili/forms.py
from django import forms

class LoginForm(forms.Form):
	user = forms.CharField(label="", help_text="", max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Username or email'}))
	password = forms.CharField(label="", help_text="", max_length=100, widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
	depth = forms.IntegerField(label="", help_text="", min_value=1, max_value=10, widget=forms.NumberInput(attrs={'placeholder': 'Depth of search'}))
	roots = forms.CharField(label="", help_text="", max_length=200, required=False, widget=forms.TextInput(attrs={'placeholder': 'Custom roots of search'}))
	rescrap = forms.BooleanField(label="Rescrap known data", help_text="", required=False)

suasor/authenticas/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from suasor.settings import BASE_HTTP_ADDRESS
from .forms import SuasorLoginForm, SuasorSignupForm
from .auxilium import validate_login, signup_user


def index(request):
    try:
        if request.session['user'] is not None:
            return redirect(BASE_HTTP_ADDRESS)
    except KeyError:
        pass # continue with logging in

    if request.method == 'POST':
        form = SuasorLoginForm(request.POST)
        if form.is_valid():
            user_id = form.cleaned_data['user_id']
            password = form.cleaned_data['password']
            if validate_login(user_id, password):
                request.session['user'] = user_id
                return redirect('praedicto:index')
            else:
                return render(request, 'authenticas/index.html', { 'form': form, 'valid': False })
    else:
        form = SuasorLoginForm()
    return render(request, 'authenticas/index.html', { 'form': form, 'valid': True })

def signup(request):
    try:
        if request.session['user'] is not None:
            return redirect(BASE_HTTP_ADDRESS)
    except KeyError:
        pass # continue with signing up

    if request.method == 'POST':
        form = SuasorSignupForm(request.POST)
        if form.is_valid():
            user_id = form.cleaned_data['user_id']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']
            if password1 == password2:
                signup_successful = signup_user(user_id, password1)
                if not signup_successful:
                    return render(request, 'authenticas/signup.html', { 'form': form, 'valid': None })
                request.session['user'] = user_id
                return redirect(BASE_HTTP_ADDRESS)
            else:
                return render(request, 'authenticas/signup.html', { 'form': form, 'valid': False })
    else:
        form = SuasorSignupForm()
    return render(request, 'authenticas/signup.html', { 'form': form, 'valid': True })

suasor/praedicto/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .auxilium import get_train_set, save_train_grades, can_continue_grading


def index(request):
    # Require user to be logged in.
    try:
        user_id = request.session['user']
    except KeyError:
        return redirect('authenticas:index')

    # Check if user can continue grading.
    can_continue = can_continue_grading(user_id)
    content = {
        'can_continue_grading': can_continue,
        'user_id': user_id
    }
    return render(request, 'praedicto/index.html', content)

def train(request, user_id_rated=None, grades=None, retrain=False):
    if user_id_rated is None:
        # Require user to be logged in.
        try:
            user_id = request.session['user']
        except KeyError:
            return redirect('authenticas:index')

        trainset = get_train_set(user_id, retrain)
        content = {
            'trainset': trainset,
            'trainset_size': len(trainset),
            'user_id': user_id
        }
        return render(request, 'praedicto/train.html', content)
    else:
        save_train_grades(user_id_rated, grades)
        return HttpResponse("Grading completed and saved to database!")

suasor/strigili/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import threading

from django.shortcuts import render, redirect
from django.http import HttpResponse

from .forms import LoginForm
from .auxilium import StrigiliThread


def index(request):
	if request.method == 'POST':
		form = LoginForm(request.POST)

		if form.is_valid():
			username = form.cleaned_data['user']
			password = form.cleaned_data['password']
			depth = form.cleaned_data['depth']
			roots = form.cleaned_data['roots']
			rescrap = form.cleaned_data['rescrap']

			thread = StrigiliThread(request, username, password, depth, roots, rescrap)
			thread.start()

			return HttpResponse("""<b>Please do not close this tab or your browser.</b>\n
				Your request is being processed...\nYou will be redirected when process finishes.""")

	else:
		form = LoginForm()

	return render(request, 'strigili/index.html', { 'form': form })

suasor/authenticas/templates/authenticas/index.html
<html>

{% load static %}

<head>
	<meta charset="utf-8">
	<title>Suasor -- Login</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/html.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/content.css' %}" />
</head>

<body>
	<div id="page">
		<div id="content">
			<div id="login_logo">
				<h1>Suasor</h1>
				<p>Log in</p>
			</div>
			<div id="login_form">
				<form method="POST">
					{% csrf_token %}
					{{ form }}
					<input type="submit" value="Login">
					<input type="button" value="Home" onclick="location.href = '{% url 'strigili:index' %}';">
				</form>
				{% if not valid %}
					<p class="error">Invalid (username, password) combination.</p>
				{% endif %}
			</div>
		</div>
	</div>
</body>

</html>

suasor/authenticas/templates/authenticas/signup.html
<html>

{% load static %}

<head>
	<meta charset="utf-8">
	<title>Suasor -- Signup</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/html.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/content.css' %}" />
</head>

<body>
	<div id="page">
		<div id="content">
			<div id="login_logo">
				<h1>Suasor</h1>
				<p>Sign up</p>
			</div>
			<div id="login_form">
				<form method="POST">
					{% csrf_token %}
					{{ form }}
					<input type="submit" value="Signup">
					<input type="button" value="Home" onclick="location.href = '{% url 'strigili:index' %}';">
				</form>
				{% if valid == False %}
					<p class="error">Passwords do not match.</p>
				{% endif %}
				{% if valid is None %}
					<p class="error">You are already registered!</p>
				{% endif %}
			</div>
		</div>
	</div>
</body>

</html>

suasor/praedicto/templates/praedicto/index.html
<html>

{% load staticfiles %}

<head>
	<meta charset="utf-8">
	<title>Suasor -- Praedicto</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/html.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/content.css' %}" />
  <script src="{% static 'js/train.js' %}"></script>
</head>

<body>
  <div class="content">
    {% if can_continue_grading is None %}
			<p>Welcome to training, {{ user_id }}! This is your first time here. Once you press "Start",
				you will be presented with {{ trainset_size }} people, for which you can decide whether
				you like him/her or not.</p>
			<button class="startBtn" onclick="location.href='{% url 'praedicto:train' retrain=True %}';">Start</button>
		{% elif can_continue_grading is False %}
			<p>Welcome to training, {{ user_id }}! You have already completed the grading process. Do you
				wish to restart grading?</p>
			<button class="startBtn" onclick="location.href='{% url 'praedicto:train' retrain=True %}';">Restart</button>
		{% else %}
			<p>Welcome to training, {{ user_id }}! You have already started a grading session which you did
				not complete. Choose, whether you want to continue or start new session.</p>
			<button class="continueBtn" onclick="location.href='{% url 'praedicto:train' retrain=False %}';">Continue</button>
			<button class="startBtn" onclick="location.href='{% url 'praedicto:train' retrain=True %}';">Restart</button>
		{% endif %}
  </div>
</body>

</html>

suasor/praedicto/templates/praedicto/train.html
<html>

{% load staticfiles %}

<head>
	<meta charset="utf-8">
	<title>Suasor -- Train Praedicto</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/html.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/content.css' %}" />
  <script src="{% static 'js/train.js' %}"></script>
  <script type="text/javascript">
    window.onload = function() {
      gradeNext(0, {{ trainset_size }}, 0);
    }
  </script>
</head>

<body>
  <div class="content">
    {% for user in trainset %}
      <div id="{{ forloop.counter0 }}" class="userWrapper" style="display: none;">
        <div class="imgWrapper">
          <img src="{% static user.user_id|add:'.jpg' %}" alt="Profile image of {{ user.user_id }}">
        </div>

        <div class="dataWrapper">
          <table>
            <tr>
              <td>Name</td>
              <td>{{ user.name }}</td>
            </tr>
            <tr>
              <td>Comes from</td>
              <td>{{ user.comes_from }}</td>
            </tr>
            <tr>
              <td>Lives in</td>
              <td>{{ user.lives_in }}</td>
            </tr>
            <tr>
              <td>Birthday</td>
              <td>{{ user.birthday }}</td>
            </tr>
            <tr>
              <td>Studies</td>
              <td>{{ user.study }}</td>
            </tr>
          </table>
        </div>

        <div class="decideGradeWrapper">
          <button class="decideGrade negative" onclick="gradeNext({{ forloop.counter }}, {{ trainset_size }}, 0);">No</button>
          <button class="decideGrade positive" onclick="gradeNext({{ forloop.counter }}, {{ trainset_size }}, 1);">Yes</button>
        </div>
      </div>
    {% endfor %}
    <button id="saveBtn" onclick="finishGrading('{{user_id}}');">Save and continue later</button>
    <div id="finishBlock" style="display: none;">
      <p>You have successfully completed grading! Now it is up to Praedicto and its magic to
        find people for you. ;)</p>
      <button id="finishBtn" onclick="finishGrading('{{user_id}}');">Save</button>
    </div>
  </div>
</body>

</html>

suasor/strigili/templates/strigili/index.html
<html>

{% load static %}

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial scale=1">
	<title>Suasor -- Strigili</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/html.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/content.css' %}" />
</head>
<body>

  <div class="menuWrap">
    <div id="logo"></div>

    <a href="#">
      <div class="menuItem">

      </div>
    </a>
  </div>

  <div id="content">
    <div class="part">
      <form method="POST">
        {% csrf_token %}
        <p class="formInfo">Facebook credentials for searching people...</p>
        {{ form }}
        <input type="submit" value="Search">
    </div>
  </div>

</body>

</html>